### ISSUE TITLE
Argument of type '(err: any) => void' is not assignable to parameter of type '() => void'.

### ISSUE THREAD

**Issue by ionush** [jaygould/nextjs-typescript-jwt-boilerplate#17]
Running the project clean after docker-compose build --no-cache and installing package.json in /client folder for the types

```
pc-client-dev | /home/app/client/node_modules/ts-node/src/index.ts:434
pc-client-dev |     return new TSError(diagnosticText, diagnosticCodes)
pc-client-dev |            ^
pc-client-dev | TSError: ⨯ Unable to compile TypeScript:
pc-client-dev | src/server.ts(26,25): error TS2769: No overload matches this call.
pc-client-dev |   The last overload gave the following error.
pc-client-dev |     Argument of type '(err: express.Errback) => void' is not assignable to parameter of type '() => void'.
pc-client-dev | 
pc-client-dev |     at createTSError (/home/app/client/node_modules/ts-node/src/index.ts:434:12)
pc-client-dev |     at reportTSError (/home/app/client/node_modules/ts-node/src/index.ts:438:19)
pc-client-dev |     at getOutput (/home/app/client/node_modules/ts-node/src/index.ts:578:36)
pc-client-dev |     at Object.compile (/home/app/client/node_modules/ts-node/src/index.ts:775:32)
pc-client-dev |     at Module.m._compile (/home/app/client/node_modules/ts-node/src/index.ts:858:43)
pc-client-dev |     at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
pc-client-dev |     at Object.require.extensions.<computed> [as .ts] (/home/app/client/node_modules/ts-node/src/index.ts:861:12)
pc-client-dev |     at Module.load (internal/modules/cjs/loader.js:1049:32)
pc-client-dev |     at Function.Module._load (internal/modules/cjs/loader.js:937:14)
pc-client-dev |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
pc-client-dev | npm ERR! code ELIFECYCLE
pc-client-dev | npm ERR! errno 1
pc-client-dev | npm ERR! @ dev: `ts-node --project ./src/tsconfig.server.json ./src/server.ts`
pc-client-dev | npm ERR! Exit status 1
pc-client-dev | npm ERR! 
pc-client-dev | npm ERR! Failed at the @ dev script.
pc-client-dev | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
pc-client-dev | 
pc-client-dev | npm ERR! A complete log of this run can be found in:
pc-client-dev | npm ERR!     /root/.npm/_logs/2020-10-01T07_45_43_655Z-debug.log
pc-client-dev exited with code 1
```

Help would be appreciated

**Comment by jaygould** [comment]
Hi mate I think I've sorted this now, thanks for letting me know. Looks like there's not an error passed in to the .listen() anymore according to [this SO](https://stackoverflow.com/questions/56291321/how-to-handle-errors-with-express-listen-in-typescript) post, so I've removed it.

I've pushed to master so give it a go and let me know if there's a problem still.

Cheers
